# Generated by Django 2.2 on 2019-06-17 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_auto_20190612_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Categoria', verbose_name='categoría del producto'),
        ),
    ]
