# Generated by Django 2.2 on 2019-07-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_auto_20190621_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riesgo', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Tipo de Riesgo',
                'verbose_name_plural': 'Tipos de Riesgos',
            },
        ),
    ]
