# Generated by Django 2.2 on 2019-07-18 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_auto_20190718_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='riesgo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='administrador.Riesgo', verbose_name='tipo de riesgo'),
            preserve_default=False,
        ),
    ]
