# Generated by Django 2.2 on 2019-08-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_producto_riesgo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
