# Generated by Django 2.2 on 2019-08-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_producto_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('1', 'unidades'), ('2', 'pares'), ('3', 'litros')], max_length=100),
        ),
    ]
