# Generated by Django 2.2 on 2019-09-09 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0010_producto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
    ]
