# Generated by Django 3.0.4 on 2020-03-23 16:42

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0011_remove_producto_estado'),
        ('ventas', '0002_venta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='administrador.Marca'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='marca', chained_model_field='marca', null=True, on_delete=django.db.models.deletion.PROTECT, to='administrador.Producto'),
        ),
    ]
