# Generated by Django 3.0.4 on 2020-10-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0011_remove_producto_estado'),
        ('compras', '0006_auto_20200322_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallecompra',
            options={'verbose_name_plural': 'Detalle de Compras'},
        ),
        migrations.RemoveField(
            model_name='compra',
            name='estado',
        ),
        migrations.AlterUniqueTogether(
            name='detallecompra',
            unique_together={('compra', 'producto')},
        ),
    ]
